name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout kode sumber
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependensi
        run: npm install

      # - name: Lakukan migrasi database
      #   run: npm run migrate
      #   env:
      #     NODE_ENV: development  # Set NODE_ENV ke "production" untuk mode produksi

      - name: Jalankan Aplikasi
        # run: npm run prod
        run:
          # Ambil alamat IP MySQL dari langkah sebelumnya
          MYSQL_IP=${{ steps.mysql_ip.outputs.mysql_ip }}
          
          # Atur variabel lingkungan untuk koneksi database
          export DB_HOST=$MYSQL_IP
          export DB_USER=root
          export DB_PASSWORD=rootpassword
          export DB_NAME=${{ secrets.DB_NAME }}
          
          # Jalankan aplikasi Node.js
          npm run prod
        env:
          PORT: ${{ secrets.PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          # DB_HOST: mysql
          # DB_USER: ${{ secrets.DB_USER }}
          # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          # DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
